# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stuff',
            field=models.BooleanField(default=False),
        ),
    ]
